version: '3.7'

services:
    postgress:
        container_name: tmp_postgres
        image: "postgres:13.2"
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - "5432:5432"
        volumes: 
            - ./data/pgdata:/var/lib/postgresql/data

    redis:
        container_name: tmp_redis
        image: redis
        ports:
            - "6379:6379"
        restart: always
